name: Delta LMS Course Availability Checker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: course_checker
  cancel-in-progress: true

jobs:
  check-courses:
    runs-on: ubuntu-latest
    steps:
      - name: Bot is Stopped
        run: |
          echo "🛑 Bot is completely stopped by user request."


